CREATE TABLE mvp_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id BIGINT REFERENCES players(id), -- Optional link
  ign TEXT NOT NULL,
  avatar TEXT,
  month TEXT, -- e.g., "January"
  year INTEGER, -- e.g., 2026
  points INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
